### ISSUE TITLE
Is not compatible with the current (which?) Notepad++ version

### ISSUE THREAD

**Issue by RobinGut999** [alex-ilin/WebEdit#2]
Hi I compiled the project but I get this error what could be the problem?
![image](https://user-images.githubusercontent.com/81331618/122633363-eea56300-d0e0-11eb-806f-c297a22d73b0.png)

**Comment by alex-ilin** [comment]
What the heck is myTest.dll, what version of Notepad++ are you using, and what does it have to do with the WebEdit project?

**Comment by alex-ilin** [comment]
Since there were no more comments from the original poster, I'm closing this issue as irrelevant.
